namespace Typebeat.Web;

/// <summary>
/// The countries an account can carry in <c>users.country_code</c>, with the display name the site
/// shows as a flag's alt text and tooltip.
///
/// <para><b>THIS LIST MIRRORS THE GAME CLIENT'S <c>typebeat.Game.Users.CountryCode</c> ENUM</b>, and
/// the direction matters: the client reads <c>country_code</c> with <c>Enum.TryParse</c>, so a code
/// stored here that the enum lacks is shown in game as the unknown flag. The entries are the enum's
/// members (and its <c>[Description]</c> names) minus the ones that are not ISO 3166-1 countries:
/// <c>Unknown</c>, the old GeoIP pseudo-codes <c>A1</c> (anonymous proxy), <c>A2</c> (satellite),
/// <c>AP</c> (Asia/Pacific), <c>O1</c> (other), and <c>EU</c>, <c>AN</c> and <c>FX</c> (Europe, the
/// dissolved Netherlands Antilles and metropolitan France). <c>WireCompat</c>'s country pin compiles
/// both and fails on any drift in either direction. A country the enum does not have yet (South
/// Sudan, <c>SS</c>, is the one Cloudflare can send today) is therefore stored as unknown until the
/// enum gains it first.</para>
///
/// <para><see cref="Unknown"/> ("XX", 001_init.sql's column default) means "no country": never
/// detected, detected as something that is not a country (Cloudflare's own <c>XX</c> and <c>T1</c>
/// for Tor), or a player who chose to show none (038_country_chosen.sql). Nothing renders for it on
/// the site.</para>
/// </summary>
public static class Countries
{
    /// <summary>The stored value for "no country".</summary>
    public const string Unknown = "XX";

    /// <summary>
    /// Whether <paramref name="code"/> is a country an account may store: exactly two upper-case
    /// letters and one of <see cref="Names"/>. <see cref="Unknown"/> is not one (it is the absence).
    /// </summary>
    public static bool IsCountry(string? code) => code is { Length: 2 } && Names.ContainsKey(code);

    /// <summary>The display name for a stored code, or null for <see cref="Unknown"/> and anything else that is not a country.</summary>
    public static string? NameOf(string? code) => IsCountry(code) ? Names[code!] : null;

    /// <summary>Every storable code, in the enum's (alphabetical by code) order.</summary>
    public static IEnumerable<string> Codes => Names.Keys;

    /// <summary>Code to display name. Ordinal keys: codes are stored upper-case and compared exactly.</summary>
    public static readonly IReadOnlyDictionary<string, string> Names = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["AD"] = "Andorra",
        ["AE"] = "United Arab Emirates",
        ["AF"] = "Afghanistan",
        ["AG"] = "Antigua and Barbuda",
        ["AI"] = "Anguilla",
        ["AL"] = "Albania",
        ["AM"] = "Armenia",
        ["AO"] = "Angola",
        ["AQ"] = "Antarctica",
        ["AR"] = "Argentina",
        ["AS"] = "American Samoa",
        ["AT"] = "Austria",
        ["AU"] = "Australia",
        ["AW"] = "Aruba",
        ["AX"] = "Aland Islands",
        ["AZ"] = "Azerbaijan",
        ["BA"] = "Bosnia and Herzegovina",
        ["BB"] = "Barbados",
        ["BD"] = "Bangladesh",
        ["BE"] = "Belgium",
        ["BF"] = "Burkina Faso",
        ["BG"] = "Bulgaria",
        ["BH"] = "Bahrain",
        ["BI"] = "Burundi",
        ["BJ"] = "Benin",
        ["BL"] = "Saint Barthelemy",
        ["BM"] = "Bermuda",
        ["BN"] = "Brunei",
        ["BO"] = "Bolivia",
        ["BQ"] = "Caribbean Netherlands",
        ["BR"] = "Brazil",
        ["BS"] = "Bahamas",
        ["BT"] = "Bhutan",
        ["BV"] = "Bouvet Island",
        ["BW"] = "Botswana",
        ["BY"] = "Belarus",
        ["BZ"] = "Belize",
        ["CA"] = "Canada",
        ["CC"] = "Cocos (Keeling) Islands",
        ["CD"] = "The Democratic Republic of the Congo",
        ["CF"] = "Central African Republic",
        ["CG"] = "Congo",
        ["CH"] = "Switzerland",
        ["CI"] = "Cote D'Ivoire",
        ["CK"] = "Cook Islands",
        ["CL"] = "Chile",
        ["CM"] = "Cameroon",
        ["CN"] = "China",
        ["CO"] = "Colombia",
        ["CR"] = "Costa Rica",
        ["CU"] = "Cuba",
        ["CV"] = "Cabo Verde",
        ["CW"] = "Curaçao",
        ["CX"] = "Christmas Island",
        ["CY"] = "Cyprus",
        ["CZ"] = "Czechia",
        ["DE"] = "Germany",
        ["DJ"] = "Djibouti",
        ["DK"] = "Denmark",
        ["DM"] = "Dominica",
        ["DO"] = "Dominican Republic",
        ["DZ"] = "Algeria",
        ["EC"] = "Ecuador",
        ["EE"] = "Estonia",
        ["EG"] = "Egypt",
        ["EH"] = "Western Sahara",
        ["ER"] = "Eritrea",
        ["ES"] = "Spain",
        ["ET"] = "Ethiopia",
        ["FI"] = "Finland",
        ["FJ"] = "Fiji",
        ["FK"] = "Falkland Islands (Malvinas)",
        ["FM"] = "Federated States of Micronesia",
        ["FO"] = "Faroe Islands",
        ["FR"] = "France",
        ["GA"] = "Gabon",
        ["GB"] = "United Kingdom",
        ["GD"] = "Grenada",
        ["GE"] = "Georgia",
        ["GF"] = "French Guiana",
        ["GG"] = "Guernsey",
        ["GH"] = "Ghana",
        ["GI"] = "Gibraltar",
        ["GL"] = "Greenland",
        ["GM"] = "Gambia",
        ["GN"] = "Guinea",
        ["GP"] = "Guadeloupe",
        ["GQ"] = "Equatorial Guinea",
        ["GR"] = "Greece",
        ["GS"] = "South Georgia and the South Sandwich Islands",
        ["GT"] = "Guatemala",
        ["GU"] = "Guam",
        ["GW"] = "Guinea-Bissau",
        ["GY"] = "Guyana",
        ["HK"] = "Hong Kong",
        ["HM"] = "Heard Island and McDonald Islands",
        ["HN"] = "Honduras",
        ["HR"] = "Croatia",
        ["HT"] = "Haiti",
        ["HU"] = "Hungary",
        ["ID"] = "Indonesia",
        ["IE"] = "Ireland",
        ["IL"] = "Israel",
        ["IM"] = "Isle of Man",
        ["IN"] = "India",
        ["IO"] = "British Indian Ocean Territory",
        ["IQ"] = "Iraq",
        ["IR"] = "Islamic Republic of Iran",
        ["IS"] = "Iceland",
        ["IT"] = "Italy",
        ["JE"] = "Jersey",
        ["JM"] = "Jamaica",
        ["JO"] = "Jordan",
        ["JP"] = "Japan",
        ["KE"] = "Kenya",
        ["KG"] = "Kyrgyzstan",
        ["KH"] = "Cambodia",
        ["KI"] = "Kiribati",
        ["KM"] = "Comoros",
        ["KN"] = "Saint Kitts and Nevis",
        ["KP"] = "Democratic People's Republic of Korea",
        ["KR"] = "South Korea",
        ["KW"] = "Kuwait",
        ["KY"] = "Cayman Islands",
        ["KZ"] = "Kazakhstan",
        ["LA"] = "Lao People's Democratic Republic",
        ["LB"] = "Lebanon",
        ["LC"] = "Saint Lucia",
        ["LI"] = "Liechtenstein",
        ["LK"] = "Sri Lanka",
        ["LR"] = "Liberia",
        ["LS"] = "Lesotho",
        ["LT"] = "Lithuania",
        ["LU"] = "Luxembourg",
        ["LV"] = "Latvia",
        ["LY"] = "Libya",
        ["MA"] = "Morocco",
        ["MC"] = "Monaco",
        ["MD"] = "Moldova",
        ["ME"] = "Montenegro",
        ["MF"] = "Saint Martin",
        ["MG"] = "Madagascar",
        ["MH"] = "Marshall Islands",
        ["MK"] = "North Macedonia",
        ["ML"] = "Mali",
        ["MM"] = "Myanmar",
        ["MN"] = "Mongolia",
        ["MO"] = "Macau",
        ["MP"] = "Northern Mariana Islands",
        ["MQ"] = "Martinique",
        ["MR"] = "Mauritania",
        ["MS"] = "Montserrat",
        ["MT"] = "Malta",
        ["MU"] = "Mauritius",
        ["MV"] = "Maldives",
        ["MW"] = "Malawi",
        ["MX"] = "Mexico",
        ["MY"] = "Malaysia",
        ["MZ"] = "Mozambique",
        ["NA"] = "Namibia",
        ["NC"] = "New Caledonia",
        ["NE"] = "Niger",
        ["NF"] = "Norfolk Island",
        ["NG"] = "Nigeria",
        ["NI"] = "Nicaragua",
        ["NL"] = "Netherlands",
        ["NO"] = "Norway",
        ["NP"] = "Nepal",
        ["NR"] = "Nauru",
        ["NU"] = "Niue",
        ["NZ"] = "New Zealand",
        ["OM"] = "Oman",
        ["PA"] = "Panama",
        ["PE"] = "Peru",
        ["PF"] = "French Polynesia",
        ["PG"] = "Papua New Guinea",
        ["PH"] = "Philippines",
        ["PK"] = "Pakistan",
        ["PL"] = "Poland",
        ["PM"] = "Saint Pierre and Miquelon",
        ["PN"] = "Pitcairn",
        ["PR"] = "Puerto Rico",
        ["PS"] = "State of Palestine",
        ["PT"] = "Portugal",
        ["PW"] = "Palau",
        ["PY"] = "Paraguay",
        ["QA"] = "Qatar",
        ["RE"] = "Reunion",
        ["RO"] = "Romania",
        ["RS"] = "Serbia",
        ["RU"] = "Russian Federation",
        ["RW"] = "Rwanda",
        ["SA"] = "Saudi Arabia",
        ["SB"] = "Solomon Islands",
        ["SC"] = "Seychelles",
        ["SD"] = "Sudan",
        ["SE"] = "Sweden",
        ["SG"] = "Singapore",
        ["SH"] = "Saint Helena",
        ["SI"] = "Slovenia",
        ["SJ"] = "Svalbard and Jan Mayen",
        ["SK"] = "Slovakia",
        ["SL"] = "Sierra Leone",
        ["SM"] = "San Marino",
        ["SN"] = "Senegal",
        ["SO"] = "Somalia",
        ["SR"] = "Suriname",
        ["ST"] = "Sao Tome and Principe",
        ["SV"] = "El Salvador",
        ["SX"] = "Sint Maarten",
        ["SY"] = "Syrian Arab Republic",
        ["SZ"] = "Eswatini",
        ["TC"] = "Turks and Caicos Islands",
        ["TD"] = "Chad",
        ["TF"] = "French Southern Territories",
        ["TG"] = "Togo",
        ["TH"] = "Thailand",
        ["TJ"] = "Tajikistan",
        ["TK"] = "Tokelau",
        ["TL"] = "Timor-Leste",
        ["TM"] = "Turkmenistan",
        ["TN"] = "Tunisia",
        ["TO"] = "Tonga",
        ["TR"] = "Türkiye",
        ["TT"] = "Trinidad and Tobago",
        ["TV"] = "Tuvalu",
        ["TW"] = "Taiwan",
        ["TZ"] = "United Republic of Tanzania",
        ["UA"] = "Ukraine",
        ["UG"] = "Uganda",
        ["UM"] = "United States Minor Outlying Islands",
        ["US"] = "United States",
        ["UY"] = "Uruguay",
        ["UZ"] = "Uzbekistan",
        ["VA"] = "Holy See (Vatican City State)",
        ["VC"] = "Saint Vincent and the Grenadines",
        ["VE"] = "Venezuela",
        ["VG"] = "Virgin Islands, British",
        ["VI"] = "Virgin Islands, U.S.",
        ["VN"] = "Vietnam",
        ["VU"] = "Vanuatu",
        ["WF"] = "Wallis and Futuna",
        ["WS"] = "Samoa",
        ["XK"] = "Kosovo",
        ["YE"] = "Yemen",
        ["YT"] = "Mayotte",
        ["ZA"] = "South Africa",
        ["ZM"] = "Zambia",
        ["ZW"] = "Zimbabwe",
    };
}
